name: JavaScript Unit Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-js:
    name: Jest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log debug information
        run: |
          npm --version
          node --version
          git --version
          php --version
          composer --version

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
            node-version-file: '.nvmrc'

      - name: NPM install
        run: npm ci --legacy-peer-deps

      - name: Run Jest Tests
        run: npm run test:unit:js
        if: ${{ success() || failure() }}
